version: "3.9"

services:
  back_db:
    image: mariadb:10.6
    container_name: back_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: superdiary
    volumes:
      - ${DATA_PATH}/back/db:/var/lib/mysql
    hostname: back_db
    networks:
      - appnet

  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    restart: unless-stopped
    environment:
      PMA_HOST: back_db
      PMA_USER: root
      PMA_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    hostname: pma
    networks:
      - appnet

  back:
    build: ./back
    container_name: back
    restart: unless-stopped
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [ gpu ]
    volumes:
      - ${DATA_PATH}/shared:/shared
      - .env:/.env
    depends_on:
      - back_db
    ports:
      - "${BACK_PORT}:80"
    hostname: back
    networks:
      - appnet

  front:
    build: ./front
    container_name: front
    restart: unless-stopped
    depends_on:
      - back
    ports:
      - "${FRONT_PORT}:8501"
    hostname: front
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
