services:
  back_db:
    image: mariadb:10.6
    container_name: back_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: superdiary
    volumes:
      - ${DATA_PATH}/back/db:/var/lib/mysql
    hostname: back_db
    networks:
      - appnet

  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    restart: unless-stopped
    environment:
      PMA_HOST: back_db
      PMA_USER: root
      PMA_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    hostname: pma
    networks:
      - appnet
    
  
  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=1h
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ${DATA_PATH}/ollama:/root/.ollama
    deploy:
      resources:
        limits:
          cpus: '4.'
          # memory: '4.'
    tty: true
    hostname: ollama
    networks:
      - appnet

  back:
    build: ./back
    container_name: back
    restart: unless-stopped
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [ gpu ]
    deploy:
      resources:
        limits:
          cpus: '4.'
          # memory: '4.'
    volumes:
      - ${DATA_PATH}/shared:/shared
      - .env:/.env
      - ${DATA_PATH}/whisper_cache:/root/.cache
      - ${DATA_PATH}/paddle:/root/.paddle
      - ${DATA_PATH}/paddleocr:/root/.paddleocr
      - ${DATA_PATH}/ollama:/ollama
      - ${DATA_PATH}/back/db:/mysql
    depends_on:
      - back_db
    ports:
      - "${BACK_PORT}:80"
    hostname: back
    networks:
      - appnet

  front:
    build: ./front
    container_name: front
    restart: unless-stopped
    depends_on:
      - back
    ports:
      - "${FRONT_PORT}:8501"
    volumes:
      - .env:/.env
    hostname: front
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
